language: go
go:
  - 1.13.x

os:
  - linux
  - osx

sudo: false

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v  ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
